// <auto-generated />
namespace BonnieYork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddVirtualStoreDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddVirtualStoreDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202212031112380_AddVirtualStoreDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
